#站点信息
site_name: Ally的魔法小屋
site_url: https://firstpioneer.github.io/cabin/
site_author: Ally
site_description: 啊吧啊吧啊吧

theme: 
    name: material
    language: zh
    features:
        - navigation.tabs  #页面顶部出现一级目录的“标签式”导航栏
        - navigation.tabs.sticky  #向下滚动时，导航栏固定在顶部
        - navigation.top  #页面顶部出现返回顶部的按钮
        - navigation.sections  #页面左侧出现二级目录的导航栏
        - navigation.expand  #点击导航项时，展开其下的子项
        - navigation.indexes  #页面左侧出现索引的导航栏
        - search.highlight 
        - search.share #页面顶部出现搜索框，用户可以在其中输入关键词搜索文档
        - toc.integrate  #将目录与页面内容集成，用户可以直接点击目录项跳转到对应位置
 # 调色板配置
    palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: follow system
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: light mode # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: darkmode

    collapse_navigation: true  #点击导航项时，收起其下的子项
    sticky_navigation: true  #固定导航栏在顶部

extra_css:
    - css/custom.css

#多语言配置示例
extra:
    alternate:
        - name: English
          link: /en/
          lang: en
        - name: 中文
          link: /zh/
          lang: zh
    #语言特定的站点名称（自定义配置，非MkDocs标准配置）
    site_name:
        en: Ally's Magic House
        zh: 啊吧啊吧啊吧


# 导航设置
nav:
    - 首页: index.md
    - 随想:
        - 随想: 
          - 随想/AI时代的到来——人类的兴起与落寞.md
          - 随想/The Games.md
          - 随想/我们只需要尝试的勇气.md
    - 关于我: about.md



#Markdown 扩展
markdown_extensions:
    - attr_list  #允许在Markdown中使用HTML属性
    - md_in_html  #允许在HTML标签中使用Markdown语法
    - admonition  #添加警告、注意、提示等 admonition 块
    - codehilite  #代码语法高亮
    - footnotes  #添加脚注
    - toc:
        permalink: true  #在目录中添加永久链接，用户可以点击目录项跳转到对应位置
        toc_depth: 3  #设置目录的深度，默认值为 3


